# model type
input_option: 0              # 1 use image and joint heat maps as input
                             # 0 use image only as input

# logger options
snapshot_save_iter: 2000        # How often do you want to save trained models
print_loss_iter: 10             # How often do you want to print the training loss
test_iter: 1000                # How often do you want to test the model stats
show_iter: 2000                 # How often do you want to show the test result
test_num: 256                   # How many images do you want to use when showing the training and testing stats

# optimization options
max_iter: 100000             # maximum number of training iterations
batch_size: 64                 # batch size
weight_decay: 0.00001        # weight decay
beta1: 0.5                    # Adam parameter
beta2: 0.999                  # Adam parameter
init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]
lr: 0.0001                    # initial learning rate
lr_policy: step               # learning rate scheduler
step_size: 100000             # how often to decay learning rate
gamma: 0.5                    # how much to decay learning rate
w_2d: 1                   # the weight of 2d loss
w_3d: 100                 # the weight of 3d loss
w_mask: 100                     # the weight of mask loss
w_reg: 10                       # the weight of regulization loss

# model options
pretrain_loss_fn: L1          # vector reconstruction loss fn [L1/L2]


# data options
num_workers: 0                              # number of data loading threads
new_size: 256                               # first resize the shortest image side to this size
data_root:  /home/lyf2/dataset/3dhand/dataset            # dataset folder location
output_pth: /home/lyf2/checkpoints/3dhand/train          # output path